[build]
rustc-wrapper = "sccache"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']

[registries]
tuna = { index = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git" }

[registry]
default = "tuna"

[net]
git-fetch-with-cli = true

